/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author piotrblaszyk
 */
public class CheckAttendance extends javax.swing.JFrame {
    Attendance attendance;

    /**
     * Creates new form CheckAttendance
     */
    public CheckAttendance() {
        initComponents();
        loadAttendance();
        studentBox.setModel(new javax.swing.DefaultComboBoxModel<>(attendance.getNames()));
        presentBox.setSelected(attendance.getPresence(0));
    }

    public void loadAttendance() {
      try {
        FileInputStream file = new FileInputStream("Attendance.dat");
        ObjectInputStream inputFile = new ObjectInputStream(file);

        try {
          attendance = ((Attendance) inputFile.readObject());
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e.getMessage());
        }

        inputFile.close();
      } catch (IOException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
        attendance = new Attendance(new String[] { "Alice", "Bob", "Charlie" });
      }
    }

  public void saveAttendance() {
    try {
      FileOutputStream file = new FileOutputStream("Attendance.dat");
      ObjectOutputStream outputFile = new ObjectOutputStream(file);

      outputFile.writeObject(attendance);
      outputFile.close();

      JOptionPane.showMessageDialog(null, "Successfully saved");
    } catch (IOException e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        presentBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alice", "Bob", "Charlie" }));
        studentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Check attendance");

        jLabel2.setText("Student");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        presentBox.setText("present");
        presentBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit)
                            .addComponent(studentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(presentBox)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(presentBox))
                .addGap(58, 58, 58)
                .addComponent(submit)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentBoxActionPerformed
        // TODO add your handling code here:
        int index = studentBox.getSelectedIndex();
        attendance.setPresence(index, presentBox.isSelected());
    }//GEN-LAST:event_presentBoxActionPerformed

    private void studentBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBoxActionPerformed
        // TODO add your handling code here:
        int index = studentBox.getSelectedIndex();
        boolean selected = attendance.getPresence(index);
        presentBox.setSelected(selected);
    }//GEN-LAST:event_studentBoxActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        attendance.printAttendance();
        saveAttendance();
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox presentBox;
    private javax.swing.JComboBox<String> studentBox;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
